# Generated by Django 4.2.11 on 2024-04-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compra", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("precio", models.FloatField()),
                ("stock_actual", models.IntegerField()),
            ],
        ),
    ]
