# Generated by Django 4.2.11 on 2024-04-21 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compra", "0002_producto"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="compra.proveedor",
            ),
        ),
    ]
