# Generated by Django 4.2.11 on 2024-04-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compra", "0003_producto_proveedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="foto",
            field=models.ImageField(
                default="producto_default.avif", upload_to="producto_img/"
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="foto",
            field=models.ImageField(default="contacto.png", upload_to="proveedor_img/"),
        ),
    ]
