# Generated by Django 4.2.11 on 2024-04-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compra", "0004_producto_foto_proveedor_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="foto",
            field=models.ImageField(
                default="producto_default.jpeg", upload_to="producto_img/"
            ),
        ),
    ]
