# Generated by Django 4.2.11 on 2024-04-27 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compra", "0006_alter_producto_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="foto",
        ),
    ]
