# Generated by Django 4.2.11 on 2024-04-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compra", "0007_remove_producto_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="foto",
            field=models.ImageField(
                default="producto_default.avif", upload_to="producto_img/"
            ),
        ),
    ]
